/**
 * 服务平台到域名模式的映射
 * 用于 --services 命令行参数和 Runner.bat 菜单
 */

const SERVICE_DOMAINS = {
  // 开发平台
  github: [
    "github.com",
    "*.github.com",
    "api.github.com",
    "raw.githubusercontent.com",
    "gist.github.com",
    "pages.github.com",
    "github.io",
    "*.github.io",
    "github.dev",
    "*.github.dev",
    "githubassets.com",
    "*.githubassets.com",
    "githubusercontent.com",
    "*.githubusercontent.com",
    "codeload.github.com",
    "objects.githubusercontent.com",
    "uploads.github.com",
    "github.blog",
    "education.github.com",
    "support.github.com",
    "status.github.com",
    "cli.github.com",
    "desktop.github.com",
    "marketplace.github.com",
    "securitylab.github.com",
    "dependabot.com",
  ],
  gitlab: [
    "gitlab.com",
    "*.gitlab.com",
    "registry.gitlab.com",
    "packages.gitlab.com",
    "gitlabcodenavigation.com",
    "gitlab.io",
    "*.gitlab.io",
    "assets.gitlab-static.net",
    "about.gitlab.com",
    "docs.gitlab.com",
    "forum.gitlab.com",
    "status.gitlab.com",
    "customers.gitlab.com",
    "license.gitlab.com",
    "version.gitlab.com",
  ],

  // 部署与托管
  vercel: ["vercel.com", "vercel.app", "*.vercel.app", "vercel.sh", "api.vercel.com"],
  netlify: ["netlify.com", "netlify.app", "*.netlify.app", "api.netlify.com", "netlifystatus.com"],
  render: ["render.com", "onrender.com", "*.onrender.com", "api.render.com"],
  railway: ["railway.app", "up.railway.app", "*.up.railway.app", "api.railway.app"],
  flyio: ["fly.io", "fly.dev", "*.fly.dev", "api.fly.io", "api.machines.dev"],

  // AI / ML
  huggingface: [
    "huggingface.co",
    "*.huggingface.co",
    "api.huggingface.co",
    "datasets-server.huggingface.co",
    "spaces.huggingface.co",
    "cdn.huggingface.co",
  ],
  wandb: ["wandb.ai", "api.wandb.ai"],
  replicate: ["replicate.com", "api.replicate.com"],

  // CI/CD 与 DevOps
  circleci: ["circleci.com", "api.circleci.com", "dl.circleci.com"],
  travisci: ["travis-ci.com", "travis-ci.org", "api.travis-ci.com"],
  jenkins: ["jenkins.io", "updates.jenkins.io", "get.jenkins.io", "plugins.jenkins.io"],
  drone: ["drone.io", "cloud.drone.io"],

  // 安全与代码质量
  snyk: ["snyk.io", "api.snyk.io", "app.snyk.io"],
  sonarcloud: ["sonarcloud.io", "api.sonarcloud.io", "sonarqube.org", "binaries.sonarsource.com"],
  codecov: ["codecov.io", "api.codecov.io", "storage.codecov.io"],
  renovate: ["mend.io", "api.renovatebot.com"],

  // 云端开发环境
  gitpod: ["gitpod.io", "*.gitpod.io", "*.gitpod.dev", "api.gitpod.io"],
  stackblitz: ["stackblitz.com", "*.stackblitz.io", "api.stackblitz.com"],
  codesandbox: ["codesandbox.io", "*.codesandbox.io", "*.csb.app", "api.codesandbox.io"],

  // 包管理与制品库
  npm: ["npmjs.com", "registry.npmjs.org", "api.npmjs.org"],
  pypi: ["pypi.org", "files.pythonhosted.org", "upload.pypi.org", "test.pypi.org"],
  maven: ["search.maven.org", "repo1.maven.org", "central.sonatype.com"],
  githubpackages: [
    "npm.pkg.github.com",
    "maven.pkg.github.com",
    "nuget.pkg.github.com",
    "rubygems.pkg.github.com",
    "ghcr.io",
  ],

  // 项目管理与协作
  atlassian: ["atlassian.com", "*.atlassian.net", "api.atlassian.com", "jira.atlassian.com"],
  linear: ["linear.app", "api.linear.app", "linear-sync.com"],
  zenhub: ["zenhub.com", "api.zenhub.com"],
  mattermost: ["mattermost.com", "*.cloud.mattermost.com"],
  slack: ["slack.com", "*.slack.com", "api.slack.com", "slack-files.com", "slack-edge.com", "slack-imgs.com"],
  discord: [
    "discord.com",
    "discord.gg",
    "discordapp.com",
    "cdn.discordapp.com",
    "media.discordapp.net",
    "gateway.discord.gg",
  ],

  // 设计与文档
  figma: ["figma.com", "api.figma.com", "www.figma.com", "help.figma.com"],
  notion: ["notion.so", "api.notion.com", "notion.site"],
  swagger: ["swagger.io", "generator.swagger.io", "validator.swagger.io", "petstore.swagger.io"],
  stoplight: ["stoplight.io", "api.stoplight.io", "*.stoplight.io"],
  mkdocs: ["mkdocs.org", "www.mkdocs.org"],
  docusaurus: ["docusaurus.io"],

  // 监控与运维
  sentry: ["sentry.io", "*.sentry.io", "*.ingest.sentry.io", "api.sentry.io"],
  prometheus: ["prometheus.io", "demo.do.prometheus.io"],
  grafana: ["grafana.com", "*.grafana.net", "api.grafana.com", "grafana.org"],
  datadog: [
    "datadoghq.com",
    "*.datadoghq.com",
    "api.datadoghq.com",
    "app.datadoghq.com",
    "browser-intake-datadoghq.com",
  ],
  newrelic: ["newrelic.com", "api.newrelic.com", "one.newrelic.com"],

  // 游戏平台
  steam: [
    "steamcdn-a.akamaihd.net",
    "steamuserimages-a.akamaihd.net",
    "cdn.akamai.steamstatic.com",
    "community.akamai.steamstatic.com",
    "avatars.akamai.steamstatic.com",
    "store.akamai.steamstatic.com",
    "community.steamstatic.com",
    "media.steampowered.com",
    "steamcommunity.com",
    "www.steamcommunity.com",
    "store.steampowered.com",
    "api.steampowered.com",
    "help.steampowered.com",
    "login.steampowered.com",
    "checkout.steampowered.com",
  ],
  twitch: [
    "irc-ws.chat.twitch.tv",
    "irc-ws-r.chat.twitch.tv",
    "passport.twitch.tv",
    "assets.twitch.tv",
    "clips-media-assets2.twitch.tv",
    "abs.hls.ttvnw.net",
    "video-edge-00252e.pdx01.abs.hls.ttvnw.net",
    "id-cdn.twitch.tv",
    "id.twitch.tv",
    "pubsub-edge.twitch.tv",
    "supervisor.ext-twitch.tv",
    "vod-secure.twitch.tv",
    "music.twitch.tv",
    "panels.twitch.tv",
    "twitch.tv",
    "www.twitch.tv",
    "m.twitch.tv",
    "app.twitch.tv",
    "badges.twitch.tv",
    "blog.twitch.tv",
    "inspector.twitch.tv",
    "stream.twitch.tv",
    "dev.twitch.tv",
    "clips.twitch.tv",
    "gql.twitch.tv",
    "vod-storyboards.twitch.tv",
    "trowel.twitch.tv",
    "countess.twitch.tv",
    "extension-files.twitch.tv",
    "vod-metro.twitch.tv",
    "pubster.twitch.tv",
    "help.twitch.tv",
    "link.twitch.tv",
    "player.twitch.tv",
    "api.twitch.tv",
    "cvp.twitch.tv",
    "client-event-reporter.twitch.tv",
    "gds-vhs-drops-campaign-images.twitch.tv",
    "us-west-2.uploads-regional.twitch.tv",
    "assets.help.twitch.tv",
    "discuss.dev.twitch.tv",
    "dashboard.twitch.tv",
  ],
  ubisoft: ["origin-a.akamaihd.net", "store.ubisoft.com"],
  roblox: [
    "www.roblox.com",
    "roblox.com",
    "web.roblox.com",
    "apis.roblox.com",
    "games.roblox.com",
    "auth.roblox.com",
    "accountsettings.roblox.com",
    "presence.roblox.com",
    "friends.roblox.com",
    "users.roblox.com",
    "gameinternationalization.roblox.com",
    "gamejoin.roblox.com",
    "locale.roblox.com",
    "metrics.roblox.com",
    "economy.roblox.com",
    "groups.roblox.com",
    "develop.roblox.com",
    "versioncompatibility.api.roblox.com",
    "clientsettings.api.roblox.com",
    "ephemeralcounters.api.roblox.com",
    "nl.roblox.com",
    "badges.roblox.com",
    "chat.roblox.com",
    "ecsv2.roblox.com",
    "thumbnails.roblox.com",
    "twostepverification.roblox.com",
    "trades.roblox.com",
    "notifications.roblox.com",
    "realtime-signalr.roblox.com",
    "assetgame.roblox.com",
    "contacts.roblox.com",
    "t.email.roblox.com",
  ],
  modio: ["binary.lge.modcdn.io", "mod.io", "static.mod.io", "api.mod.io", "docs.mod.io", "beta.mod.io", "blog.mod.io", "auth.mod.io"],
  nexusmods: [
    "nexusmods.com",
    "www.nexusmods.com",
    "staticdelivery.nexusmods.com",
    "cf-files.nexusmods.com",
    "staticstats.nexusmods.com",
    "users.nexusmods.com",
    "files.nexus-cdn.com",
    "premium-files.nexus-cdn.com",
    "supporter-files.nexus-cdn.com",
  ],

  // 媒体与内容
  spotify: [
    "open.spotify.com",
    "spotify.com",
    "www.spotify.com",
    "apresolve.spotify.com",
    "api-partner.spotify.com",
  ],
  youtube: ["img.youtube.com"],
  pinterest: [
    "pinterest.com",
    "www.pinterest.com",
    "pinimg.com",
    "sm.pinimg.com",
    "s.pinimg.com",
    "i.pinimg.com",
    "de.pinterest.com",
    "s2.pinimg.com",
  ],
  artstation: [
    "artstation.com",
    "www.artstation.com",
    "cdn-learning.artstation.com",
    "cdna.artstation.com",
    "cdn.artstation.com",
    "cdnb.artstation.com",
    "aleksi.artstation.com",
    "aroll.artstation.com",
    "dya.artstation.com",
    "yourihoek.artstation.com",
    "rishablue.artstation.com",
    "ww.artstation.com",
    "magazine.artstation.com",
  ],
  imgur: [
    "imgur.com",
    "i.imgur.com",
    "s.imgur.com",
    "i.stack.imgur.com",
    "m.imgur.com",
    "api.imgur.com",
    "p.imgur.com",
    "www.imgur.com",
    "fufufu23.imgur.com",
    "thepoy.imgur.com",
    "blog.imgur.com",
    "cellcow.imgur.com",
    "t.imgur.com",
  ],
  fandom: ["fandom.com", "www.fandom.com"],

  // 网络服务与 CDN
  googlefonts: ["fonts.gstatic.com", "themes.googleusercontent.com", "ajax.googleapis.com", "fonts.googleapis.com", "maxcdn.bootstrapcdn.com"],
  gravatar: ["gravatar.com", "secure.gravatar.com", "www.gravatar.com"],
  googletranslate: ["translate.google.cn", "translate.googleapis.com", "translate-pa.googleapis.com", "translate.google.com"],
  googlesearch: ["google.com", "www.google.com"],
  hcaptcha: [
    "hcaptcha.com",
    "assets.hcaptcha.com",
    "imgs.hcaptcha.com",
    "www.hcaptcha.com",
    "docs.hcaptcha.com",
    "js.hcaptcha.com",
    "newassets.hcaptcha.com",
    "imgs3.hcaptcha.com",
  ],
  arkose: [
    "client-api.arkoselabs.com",
    "epic-games-api.arkoselabs.com",
    "cdn.arkoselabs.com",
    "prod-ireland.arkoselabs.com",
  ],
  docker: ["hub.docker.com"],
  greasyfork: ["greasyfork.org", "update.greasyfork.org"],
  onedrive: ["storage.live.com", "skyapi.onedrive.live.com", "onedrive.live.com", "onedrive.live"],
  mega: [
    "mega.co.nz",
    "g.cdn1.mega.co.nz",
    "www.mega.co.nz",
    "userstroage.mega.co.nz",
    "g.api.mega.co.nz",
    "mega.io",
    "g.static.mega.co.nz",
    "mega.nz",
    "www.mega.nz",
  ],
  dropbox: [
    "aem.dropbox.com",
    "dropbox.com",
    "www.dropbox.com",
    "dl.dropboxusercontent.com",
    "uc07aaf207f16a978a3dbc24a1c9.dl.dropboxusercontent.com",
    "uc87442e427766fe8cf2a7a07827.dl.dropboxusercontent.com",
    "uc957f785cc03b9b273234fd24f9.dl.dropboxusercontent.com",
    "ucc541451e9df780e40777d477eb.dl.dropboxusercontent.com",
    "ucb277f9a438d6b3f4ea2147ac26.dl.dropboxusercontent.com",
    "uc4b4b602d4b01e27782f92ce984.dl.dropboxusercontent.com",
    "uc9c83355d6aa8bc75f7f597c7d6.dl.dropboxusercontent.com",
    "ucaf37cba09486e69c215bdfe2e2.dl.dropboxusercontent.com",
    "uca3a40eb53259715309022eb9fd.dl.dropboxusercontent.com",
  ],
};

// 有序服务列表，用于菜单显示
const SERVICE_LIST = [
  { code: "github", label: "GitHub" },
  { code: "gitlab", label: "GitLab" },
  { code: "vercel", label: "Vercel" },
  { code: "netlify", label: "Netlify" },
  { code: "render", label: "Render" },
  { code: "railway", label: "Railway" },
  { code: "flyio", label: "Fly.io" },
  { code: "huggingface", label: "Hugging Face" },
  { code: "wandb", label: "Weights & Biases" },
  { code: "replicate", label: "Replicate" },
  { code: "circleci", label: "CircleCI" },
  { code: "travisci", label: "Travis CI" },
  { code: "jenkins", label: "Jenkins" },
  { code: "drone", label: "Drone" },
  { code: "snyk", label: "Snyk" },
  { code: "sonarcloud", label: "SonarCloud" },
  { code: "codecov", label: "Codecov" },
  { code: "renovate", label: "Mend/Renovate" },
  { code: "gitpod", label: "Gitpod" },
  { code: "stackblitz", label: "StackBlitz" },
  { code: "codesandbox", label: "CodeSandbox" },
  { code: "npm", label: "npm" },
  { code: "pypi", label: "PyPI" },
  { code: "maven", label: "Maven Central" },
  { code: "githubpackages", label: "GitHub Packages" },
  { code: "atlassian", label: "Atlassian (Jira/Confluence)" },
  { code: "linear", label: "Linear" },
  { code: "zenhub", label: "ZenHub" },
  { code: "mattermost", label: "Mattermost" },
  { code: "slack", label: "Slack" },
  { code: "discord", label: "Discord" },
  { code: "figma", label: "Figma" },
  { code: "notion", label: "Notion" },
  { code: "swagger", label: "Swagger" },
  { code: "stoplight", label: "Stoplight" },
  { code: "mkdocs", label: "MkDocs" },
  { code: "docusaurus", label: "Docusaurus" },
  { code: "sentry", label: "Sentry" },
  { code: "prometheus", label: "Prometheus" },
  { code: "grafana", label: "Grafana" },
  { code: "datadog", label: "Datadog" },
  { code: "newrelic", label: "New Relic" },
  { code: "steam", label: "Steam" },
  { code: "twitch", label: "Twitch" },
  { code: "ubisoft", label: "Ubisoft / Uplay" },
  { code: "roblox", label: "Roblox" },
  { code: "modio", label: "mod.io" },
  { code: "nexusmods", label: "Nexus Mods" },
  { code: "spotify", label: "Spotify" },
  { code: "youtube", label: "YouTube (图片)" },
  { code: "pinterest", label: "Pinterest" },
  { code: "artstation", label: "ArtStation" },
  { code: "imgur", label: "Imgur" },
  { code: "fandom", label: "Fandom" },
  { code: "googlefonts", label: "Google Fonts / CDN" },
  { code: "gravatar", label: "Gravatar" },
  { code: "googletranslate", label: "Google 翻译" },
  { code: "googlesearch", label: "Google 搜索" },
  { code: "hcaptcha", label: "hCaptcha" },
  { code: "arkose", label: "Arkose Labs" },
  { code: "docker", label: "Docker Hub" },
  { code: "greasyfork", label: "GreasyFork" },
  { code: "onedrive", label: "OneDrive" },
  { code: "mega", label: "MEGA" },
  { code: "dropbox", label: "Dropbox" },
];

// 按原有分类聚合服务，用于快速全选某类平台
const CATEGORY_SERVICES = {
  base: [
    "github",
    "gitlab",
    "vercel",
    "netlify",
    "render",
    "railway",
    "flyio",
    "huggingface",
    "wandb",
    "replicate",
    "circleci",
    "travisci",
    "jenkins",
    "drone",
    "snyk",
    "sonarcloud",
    "codecov",
    "renovate",
    "gitpod",
    "stackblitz",
    "codesandbox",
    "npm",
    "pypi",
    "maven",
    "githubpackages",
    "atlassian",
    "linear",
    "zenhub",
    "mattermost",
    "slack",
    "discord",
    "figma",
    "notion",
    "swagger",
    "stoplight",
    "mkdocs",
    "docusaurus",
    "sentry",
    "prometheus",
    "grafana",
    "datadog",
    "newrelic",
  ],
  gaming: ["steam", "twitch", "ubisoft", "roblox", "modio", "nexusmods"],
  media: ["spotify", "youtube", "pinterest", "artstation", "imgur", "fandom"],
  network: [
    "googlefonts",
    "gravatar",
    "googletranslate",
    "googlesearch",
    "hcaptcha",
    "arkose",
    "docker",
    "greasyfork",
    "onedrive",
    "mega",
    "dropbox",
  ],
};

function getServiceDomains(codes) {
  const domains = [];
  for (const code of codes) {
    if (code === "all") {
      for (const list of Object.values(SERVICE_DOMAINS)) {
        domains.push(...list);
      }
      return Array.from(new Set(domains));
    }
    const list = SERVICE_DOMAINS[code];
    if (list) {
      domains.push(...list);
    }
  }
  return Array.from(new Set(domains));
}

module.exports = {
  SERVICE_DOMAINS,
  SERVICE_LIST,
  CATEGORY_SERVICES,
  getServiceDomains,
};
